### ISSUE TITLE
Data Manupulation for a Personal Finance Tracker 

### ISSUE THREAD

**Issue by aditya-ghosh2992** [Microsoft-LSA-Nexus-Chapter/Data-Science-Snippets#15]
Key feature of Data Manipulation :

Data Cleaning: Handle missing values, outliers, and inconsistencies.
Data Transformation: Convert raw data into a suitable format for analysis.
Data Aggregation: Group and summarize data to identify trends and patterns.
Data Visualization: Create informative charts and graphs to communicate insights.

**Comment by Souhridya-Patra** [comment]
@aditya-ghosh2992 Can you assign this to me?

**Comment by aditya-ghosh2992** [comment]
pr merged
